output: Wonderful gradescope
stdout_visibility: visible
test_parts:
  - run: "make tests"
    tests:
      - id: TestID
        max_score: 10
        name: Testing for Foo
        number: "1.1"
        visibility: hidden
        tags:
          - a
          - b
          - c
      - id: TestId2
        max_score: 20
        name: testing for bar
        number: "1.2"
        visibility: "visible"
        tags:
          - b
          - c
          - d

  - run: "make tests2"
    tests:
      - id: CompileTest
        max_score: 10
        name: Compilation test
        output: Test that the code actually compiles.
        visibility: visible
